import { ArrowRight, BookOpenCheck, Calculator, Info } from 'lucide-react';
import { Link } from 'wouter';
import { FILIERES, formatNumber } from '@/data/calculator';

export function HowItWorks() {
  return <div className="mx-auto max-w-6xl px-5 py-10 lg:px-8 lg:py-16">
    <div className="max-w-3xl"><div className="eyebrow mb-3">La méthode, sans secret</div><h1 className="font-display text-4xl font-extrabold tracking-[-.06em] sm:text-6xl">Comprendre avant de calculer.</h1><p className="mt-5 max-w-2xl text-lg leading-8 text-[hsl(var(--muted-foreground))]">Le score CPGE se lit comme une addition de quatre repères. Voici la formule officielle, puis le rôle de chaque élément.</p></div>
    <section className="mt-12 rounded-[24px] bg-[hsl(var(--primary))] p-6 text-[hsl(var(--primary-foreground))] sm:p-9"><div className="flex items-center gap-3 text-sm font-bold"><Calculator size={18} /> Formule officielle</div><div className="mt-7 overflow-x-auto font-mono text-xl leading-10 sm:text-3xl">N = N1 + (N2 − 10) + (170 × N3 / 20) + (10 × N4 / 25)</div><p className="mt-5 max-w-2xl text-sm leading-6 opacity-75">Les notes saisies avec des décimales sont conservées avec leur précision complète pendant tout le calcul. L’affichage final est arrondi à deux décimales.</p></section>
    <section className="mt-16"><div className="eyebrow mb-3">Les quatre composantes</div><h2 className="font-display text-3xl font-extrabold tracking-[-.05em]">Chaque nombre a son histoire.</h2><div className="mt-8 grid gap-3 sm:grid-cols-2">{[
      ['N1', 'Le parcours scolaire', '10 points si aucune des deux années du bac n’a été redoublée, 5 points si la première année a été redoublée, 0 point si la terminale a été redoublée. Les deux situations ne peuvent pas être combinées.'],
      ['N2', 'Les notes du bac', 'N2 = (M1 + 2 × M2) / 3. M1 représente la première année, M2 la deuxième année : cette dernière compte donc double dans la moyenne.'],
      ['N3', 'Les matières qualifiantes', 'N3 est la moyenne pondérée des matières de votre filière. Pour chaque matière, la note est multipliée par son coefficient, puis la somme est divisée par le total des coefficients.'],
      ['N4', 'Le conseil de classe', 'N4 est la note donnée par le conseil de classe, sur 25. Elle contribue au score à hauteur de 10 × N4 / 25.'],
    ].map(([key, title, text]) => <article key={key} className="rounded-2xl border border-[hsl(var(--border))] bg-[hsl(var(--card)/.55)] p-6"><span className="font-mono text-sm font-bold text-[hsl(var(--primary))]">{key}</span><h3 className="mt-8 font-display text-xl font-bold">{title}</h3><p className="mt-3 text-sm leading-7 text-[hsl(var(--muted-foreground))]">{text}</p></article>)}</div></section>
    <section className="mt-16"><div className="flex items-end justify-between gap-4"><div><div className="eyebrow mb-3">Référentiel des matières</div><h2 className="font-display text-3xl font-extrabold tracking-[-.05em]">Coefficients par filière</h2></div><Info className="mb-1 hidden text-[hsl(var(--accent))] sm:block" /></div><div className="mt-8 overflow-hidden rounded-2xl border border-[hsl(var(--border))] bg-[hsl(var(--card)/.6)]"><div className="hidden grid-cols-[100px_1fr_110px] gap-4 border-b border-[hsl(var(--border))] bg-[hsl(var(--secondary)/.5)] px-5 py-3 text-[11px] font-bold uppercase tracking-[.1em] text-[hsl(var(--muted-foreground))] sm:grid"><span>Filière</span><span>Matière</span><span className="text-right">Coefficient</span></div>{Object.entries(FILIERES).map(([code, data], filiereIndex) => <div key={code} className={`grid gap-3 px-5 py-5 sm:grid-cols-[100px_1fr_110px] sm:gap-4 ${filiereIndex ? 'border-t border-[hsl(var(--border))]' : ''}`}><div className="flex items-center gap-2"><span className="font-mono font-bold text-[hsl(var(--primary))]">{code}</span><span className="text-xs text-[hsl(var(--muted-foreground))] sm:hidden">{data.label}</span></div><div className="grid gap-2 sm:grid-cols-2">{data.subjects.map((subject) => <div key={subject.name} className="flex justify-between gap-4 text-sm"><span className="text-[hsl(var(--muted-foreground))]">{subject.name}</span><span className="font-mono font-bold sm:hidden">{formatNumber(subject.coefficient, subject.coefficient % 1 ? 2 : 0)}</span></div>)}</div><div className="hidden text-right font-mono text-sm font-bold text-[hsl(var(--primary))] sm:block">{data.subjects.map((subject) => <div className="mb-2 last:mb-0" key={subject.name}>{formatNumber(subject.coefficient, subject.coefficient % 1 ? 2 : 0)}</div>)}</div></div>)}</div></section>
    <section className="mt-14 flex flex-col items-start justify-between gap-5 rounded-[24px] border border-[hsl(var(--border))] bg-[hsl(var(--secondary)/.46)] p-6 sm:flex-row sm:items-center sm:p-8"><div><BookOpenCheck className="text-[hsl(var(--primary))]" size={24} /><h2 className="mt-4 font-display text-2xl font-extrabold">Prêt à faire le vôtre ?</h2><p className="mt-2 text-sm text-[hsl(var(--muted-foreground))]">Le calcul guidé prend moins d’une minute.</p></div><Link href="/calculateur" data-testid="button-how-calculator" className="inline-flex items-center gap-2 rounded-full bg-[hsl(var(--primary))] px-5 py-3 text-sm font-bold text-[hsl(var(--primary-foreground))]">Ouvrir le calculateur <ArrowRight size={16} /></Link></section>
  </div>;
}